### ISSUE TITLE
スマートフォンにおけるLogo.pngの縮小化

### ISSUE THREAD

**Issue by wakiyamap** [Code-for-Fukuoka/covid19-fukuoka#24]
## 改善詳細 / Details of Improvement
スマートフォン版のヘッダーの画像が大きく、肝心の本文表示が狭くなっているように思えます。
ブランド等何かあるのかちょっと判断がつかないのですが、検討していただけると幸いです。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/7189933/78555150-60302300-7847-11ea-8d1e-e28695ae6bf9.png)

## 期待する見せ方・挙動 / Expected behavior
![image](https://user-images.githubusercontent.com/7189933/78555273-a5545500-7847-11ea-979b-558bca1ff6a2.png)

## 動作環境・ブラウザ / Environment
- iOS / Android

**Comment by yoshiosakamoto** [comment]
スマホ表示のロゴを50pxに修正しました。

**Comment by wakiyamap** [comment]
ありがとうございます！
