### ISSUE TITLE
相談の手順のフロー作成

### ISSUE THREAD

**Issue by tokunaga33** [Code-for-Fukuoka/covid19-fukuoka#42]
## 改善詳細 / Details of Improvement
- 福岡県版の相談の手順を作成する

## 期待する見せ方・挙動 / Expected behavior
- 色は緑→青（福岡県版のベース色）に変更
- 添付の通り、東京都版から修正（他、東京の文言等は要修正）
[福岡県版イメージ新型コロナウイルス感染症にかかる相談窓口について.pdf](https://github.com/Code-for-Fukuoka/covid19-fukuoka/files/4467092/default.pdf)

**Comment by tokunaga33** [comment]
@NM502i 
こちらの福岡県版の相談の手順の作成もよければお願いしたいです。
上記添付のファイルの内容で対応いただけたらと思います。
確認の上、可能であればお願いします。

**Comment by NM502i** [comment]
@tokunaga33
こちらの書き込みに気づかず、返信遅れて失礼しました。
福岡県版の手順作成、了解しました。
明日中にはお見せできると思いますが、もし作業が遅れそうならご連絡差し上げます。

**Comment by tokunaga33** [comment]
@NM502i 
ありがとうございます！
大丈夫です。できたタイミングでお知らせいただければ。
快諾いただき、ありがとうございます😊

**Comment by NM502i** [comment]
@tokunaga33
>色は緑→青（福岡県版のベース色）に変更
>添付の通り、東京都版から修正（他、東京の文言等は要修正）
>福岡県版イメージ新型コロナウイルス感染症にかかる相談窓口について.pdf

上記の変更依頼を反映させたバージョンを作成しましたので内容をご確認ください
（もうかなりデータを修正いただいていたので作業はほぼ細かい箇所の変更で済みました）。
http://covid19fukuoka-ken.s3-website-ap-northeast-1.amazonaws.com/flow/

その他変更必要な箇所ありましたらご指摘のほどよろしくお願いします。

**変更依頼・元ファイル（Development）の下記の部分を更に変更しました**
1.  帰国者・接触者相談センターのリンク先を変更
before:https://www.pref.fukuoka.lg.jp/contents/covid-19-portal.html#A1-5-1
after:   https://www.pref.fukuoka.lg.jp/contents/covid-19-portal.html#b1-2
2. 元ファイルの文言変更
before:新型コロナ受診相談窓口（日本語のみ）
after:   新型コロナ受診相談窓口

 ## スクリーンショット（PC）
![covid19_fukuoka-ken_flow_pc](https://user-images.githubusercontent.com/48637162/79390247-56769000-7faa-11ea-937c-6b03cf323708.png)

 
 ## スクリーンショット（SP）
![covid19_fukuoka-ken_flow_sp](https://user-images.githubusercontent.com/48637162/79390270-61312500-7faa-11ea-8c3d-09b32c221a88.png)

**Comment by tokunaga33** [comment]
@NM502i 
ありがとうございます！
リンク等福岡県に確認しますね。

**Comment by yoshiosakamoto** [comment]
福岡県から連絡があり、（日本語のみ）は残しておいてほしいとの事です。
修正よろしくお願いします！

**Comment by NM502i** [comment]
修正作業を行いました。

**Comment by yoshiosakamoto** [comment]
ありがとうございます！
development環境にプルリクお願いできますでしょうか？
テスト環境で福岡県の最終確認としたいと思いm佐生。

**Comment by yoshiosakamoto** [comment]
@NM502i ありがとうございます！
福岡県に最終確認中です。
もしよろしければ、引き続きOwner権限で参加していただけると大変心強いです(^^)

**Comment by yoshiosakamoto** [comment]
@NM502i 本番環境に反映しました！
本件クローズとさせていただきます。

**Comment by yoshiosakamoto** [comment]
@NM502i ありがとうございました！
