### ISSUE TITLE
陽性患者数（区市町村別） 作成

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#49]
## 改善詳細 / Details of Improvement
- 福岡県版の陽性患者数（区市町村別）を作成する。

**Comment by yoshiosakamoto** [comment]
福岡県からは、陽性患者数の棒グラフを、福岡市、北九州市、福岡県（それ以外）で分けれないかという相談が来ているところです。
あまり細かく分けると、県民のみなさんの不安をあおる事にならないかという懸案もあります。
見せ方を検討していく必要があるかもしれません。

**Comment by uttnaoki** [comment]
- 「陽性患者数」の棒グラフを、福岡市、北九州市、福岡県（それ以外）で分ける場合、
現在「陽性患者数」で読み込んでいるデータはどの地域のものかわからないため、
「陽性患者の属性」で読み込んでいるデータを利用（集計）する処理になるのでしょうか？
それとも現在「陽性患者数」で読み込んでいるデータが後々変わる予定なのでしょうか？
- また、東京版では各地域ごとの陽性患者数を表で可視化しているのですが、
福岡版としては上記の通りグラフで表現する。という認識であってますか？

**Comment by yoshiosakamoto** [comment]
福岡県からは、「陽性患者発表情報（陽性患者の属性）」に新たにフラグを追加するので、それを利用して棒グラフを分けてほしいという依頼が来ています。まだデータが無いため実装していません。なので福岡県版では、まずは棒グラフ3つに分ける予定です。
市区町村別に分けるとしても、福岡市は、区が入っていたり、いなかったりのため、まずは市町村別で表示する事になると思います。表よりは円グラフの方が見やすい気がしています。
市町村別、年齢別などの円グラフがあると、傾向が見やすいですかね？

**Comment by uttnaoki** [comment]
データ（フラグ）追加後に棒グラフを３つに分ける予定ということですね。理解しました。
現時点でこのissueが必要でなければcloseをお願いします。

年齢別円グラフはよくテレビ（全国）でも出ているので関心が高いかもしれないですね。

**Comment by NM502i** [comment]
@yoshiosakamoto 
@uttnaoki 

横から失礼します。
こちらのIssuesについてご提案があります。

こちらの機能について、自分もあれば便利だなと思っており、
・「陽性患者の属性」の「居住地」からデータをソートする
という方法で、取り急ぎプロトタイプを作成しました。

http://covid19fukuoka-ken.s3-website-ap-northeast-1.amazonaws.com/
→「陽性患者数（居住地別）」を参照

各地区の比較グラフだけでなく、セレクターで各地区の陽性患者数グラフも表示できるようにしています
※ただし現在下記のバグあり（修正箇所はすでに把握済み）

市区町村名のデータ提供が現在進行中とのことですが、このプロトタイプを叩き台に表示・機能・文言など修正していけば、（データ提供が開始された時にデータの参照元の変更さえ行えば）実装が比較的早く行えるのではと思いますので、もしよろしければ修正指示をお願いできますでしょうか。

![area_graph_01](https://user-images.githubusercontent.com/48637162/79813234-0470a880-83b6-11ea-9e5c-28b8f99ba89d.png)
![area_graph_02](https://user-images.githubusercontent.com/48637162/79813313-400b7280-83b6-11ea-86e3-567c7f19e9cf.png)
![area_graph_03](https://user-images.githubusercontent.com/48637162/79813249-0c304d00-83b6-11ea-9a22-804e4a076a73.png)

**既存のバグ**
・「日別・累計」のトグルボタンで、選択中の項目を再クリックできてしまう
・ 「すべて」→「各地区」にグラフ表示を変更した際、月の表示が消える
・「各地区（累計）」→「すべて」にグラフ表示を変更した際、各地区の表示が消える

**Comment by yoshiosakamoto** [comment]
@NM502i 
いいですね！福岡県に提案してみます。

**Comment by uttnaoki** [comment]
@NM502i
見た目もすごくきれいで実装も早いですね。ソースがあれば見て勉強させていただきたいです。
一つ気になったのは、棒グラフの横軸（日付）について、データの無い日がある場合、その日のデータ（0件）が表示できず、横軸（日付）の間隔が一定にならないのは検討しないといけなさそうですね（データ側で用意対応するのかフロントで対応するのか）。

**Comment by yoshiosakamoto** [comment]
@NM502i 提案頂いたグラフでお願いしたいという事になりました。
問題点が修正されたら、developmentにcommitして頂けますでしょうか？

**Comment by NM502i** [comment]
@yoshiosakamoto 
遅ればせながら修正版をdevelopmentにコミットしておきました。

**Comment by NM502i** [comment]
@uttnaoki 
大変遅ればせながらご指摘ありがとうございます。

> 一つ気になったのは、棒グラフの横軸（日付）について、データの無い日がある場合、その日のデータ（0件）が表示できず、横軸（日付）の間隔が一定にならないのは検討しないといけなさそうですね

確かに
・新規陽性者がカウントされない日＝データが無い日
となっているのは仕様として完全に問題があるので、その部分は修正させていただきました。
ただまだ見せ方としては改良の余地がありそうですので、余裕があればupdateしたいと思います（東京都のように横スクロール可能にするなど）。
貴重なご意見、とても助かりました。

**・Before**
![area_chart_before](https://user-images.githubusercontent.com/48637162/80188155-bc6ab380-864b-11ea-8132-7b3c1a45830e.png)
**・After**
![area_chart_after](https://user-images.githubusercontent.com/48637162/80189593-df966280-864d-11ea-9d3f-1ce4bc07b2ba.png)
