### ISSUE TITLE
スクロールバーとアイコンが被っている

### ISSUE THREAD

**Issue by cohky16** [Code-for-Fukuoka/covid19-fukuoka#50]
サイトを見ていて少し気になったので、イシューを作成させていただきます。

## 改善詳細 / Details of Improvement
- スクロールバーとアイコンが被らないようにする

## スクリーンショット / Screenshot
![0003CB75-0F37-43E2-8481-41C8A9B5FCC9_4_5005_c](https://user-images.githubusercontent.com/45580421/79735289-ff1e4a00-8332-11ea-9f85-99d4ae471011.jpeg)

## 期待する見せ方・挙動 / Expected behavior
- スクロールバーとアイコンが被らないこと

## 動作環境・ブラウザ / Environment
- macOS
- Chrome / Safari

**Comment by NM502i** [comment]
@cohky16 

こちら対応してDevelopmentにcommitしました。

## スクリーンショット
**・Before**
![navigation_space_before](https://user-images.githubusercontent.com/48637162/80290873-8b8d9a00-8783-11ea-8a54-08ee992619d3.png)

**・After**
![navigation_space_after](https://user-images.githubusercontent.com/48637162/80290878-8fb9b780-8783-11ea-90e9-333031aef845.png)

## 動作確認・ブラウザ
* macOS（Catalina 10.15.4）
* Chrome（macOS:81.0.4044.113） / Safari（macOS:13.1 (15609.1.20.111.8), iOS:13.0.5） / Firefox （macOS:75.0 (64 ビット)）

**Comment by cohky16** [comment]
@NM502i 
確認できました！ありがとうございます！
