### ISSUE TITLE
「陽性患者数（居住地別）」の見せ方に関する提案

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#54]
## 改善詳細 / Details of Improvement
「陽性患者数（居住地別）」の"すべて"について、
他の"福岡市"や"北九州市"と同じように並べると見せ方の一貫性がないように思います。
具体的に、「陽性患者数（居住地別）」で可視化しているデータは以下のようになっています。
- "すべて"
　最新の一日のデータ
- "福岡市", "北九州市", "福岡県（それ以外）", "その他"
　最古から最新までのデータ

上記の理由から、「陽性患者数（居住地別）」の"すべて"は別のカードへ移すか"すべて"の部分で現在の「陽性患者数」のグラフを表示するといいんじゃないかと考えています。
ご意見を伺いたいです。

**Comment by NM502i** [comment]
@uttnaoki 
基本的に1カード＝1種類のグラフという仕様なのに、現在2種類のグラフが表示されるため統一感がないという提案でよろしいでしょうか（確かに気にはなっていました）。

>上記の理由から、「陽性患者数（居住地別）」の"すべて"は別のカードへ移すか"すべて"の部分で現在の「陽性患者数」のグラフを表示するといいんじゃないかと考えています。

”すべて”の部分で現在の「陽性患者数」のグラフを表示すると、同じ表示のグラフが2つあることになってちょっと引っかかるので、まずは

**1. 「陽性患者数（居住地別）」の"すべて"は別のカードに移す**

**2. 既存の「陽性患者数」グラフで居住地別の表示を可能にする**

という仕様で改良版のサンプルを作成してみたいと思います。

最終的にはownerおよび県担当者の方の判断になるとは思いますが、そちらのサンプルを確認後、またご意見を伺ってもよろしいでしょうか。

**Comment by uttnaoki** [comment]
@NM502i 
レスポンスしていただいてありがとうございます。

> 基本的に1カード＝1種類のグラフという仕様なのに、現在2種類のグラフが表示されるため統一感がないという提案でよろしいでしょうか（確かに気にはなっていました）。

その認識です。

> ”すべて”の部分で現在の「陽性患者数」のグラフを表示すると、同じ表示のグラフが2つあることになってちょっと引っかかるので、

自分も同じグラフが２つあるのは良くないと思います。
そこで、自分の提案としては「陽性患者数」と「陽性患者数（居住地別）」を統合するとよいのではと考えています。

統合方法として、@NM502i さんが今提案してくださった

> 2. 既存の「陽性患者数」グラフで居住地別の表示を可能にする

がいいと考えています。ただし、実装方法としては
「陽性患者数（居住地別）」の"すべて"に「陽性患者数」のグラフを表示し、
「陽性患者数（居住地別）」のグラフ名を「陽性患者数」へ修正すると
実装しやすいのではないかと考えています（つまり削除するのは現在の「陽性患者数」のカード）。

**Comment by NM502i** [comment]
@uttnaoki 
こちらかなり遅くなりましたが、サンプルを実装しました。
>「陽性患者数（居住地別）」の"すべて"に「陽性患者数」のグラフを表示し、
>「陽性患者数（居住地別）」のグラフ名を「陽性患者数」へ修正すると
>実装しやすいのではないかと考えています（つまり削除するのは現在の「陽性患者数」のカード）。

**・居住地別の陽性患者数のグラフ**
については上記の仕様で問題ないと思います。またそれとは別に
**・居住地ごとの陽性患者数を比較できるグラフ**
もあった方がよいと思いますので、こちらは円グラフにして別のカードに分けてみました。
この形なら参照しているデータは同じでも、「居住地別の陽性患者数」と同じグラフにはならないかと。
サンプルは以下のURLになります。
http://covid19fukuoka-ken.s3-website-ap-northeast-1.amazonaws.com/

![area_chart](https://user-images.githubusercontent.com/48637162/80898026-9030f000-8d39-11ea-956c-823cc5811f64.png)
![area_chart_tooltips](https://user-images.githubusercontent.com/48637162/80898039-a2ab2980-8d39-11ea-933a-48fbe820cc26.png)

**Comment by uttnaoki** [comment]
@NM502i

以下について、
> ・居住地別の陽性患者数のグラフ
> については上記の仕様で問題ないと思います。またそれとは別に
> ・居住地ごとの陽性患者数を比較できるグラフ

- 居住地別の陽性患者数のグラフ
サンプルを確認しました。
「陽性患者数」の動作について、私のイメージと完全に一致しています。
勝手に本番環境へ移してしまってよいのかわかっておりませんが、
私はこのまま反映させてよいのではと考えています。

- 居住地ごとの陽性患者数を比較できるグラフ
陽性患者数（居住地別）の元の"すべて"を別のカードへ移した場合について、
円グラフによる可視化は私も提案しようと考えていました。
扱うデータも１日だけのものではなく、累計を扱うように修正されていてすごくいいですね。
また詳細データをマウスオーバーで見れるようになっているのもいいですね。

余談ですが、コミットのログを見て思ったところがありまして、
@NM502i さんの開発環境のgitのconfigとgithubのconfigは一致していないのではないでしょうか。

**Comment by yoshiosakamoto** [comment]
円グラフわかりやすいですね。こっちの方が良いのではないかと思います。福岡県にも提案してみます。

**Comment by NM502i** [comment]
@uttnaoki こちらまた返信がすごく遅れまして大変失礼しました。
確認ありがとうございます。
自分もこちらのほうが見やすいので、可能ならアップデートできればと考えています。
>余談ですが、コミットのログを見て思ったところがありまして、
>@NM502i さんの開発環境のgitのconfigとgithubのconfigは一致していないのではないでしょうか。
ローカルの開発環境を再構築しました。
こちらもご指摘ありがとうございました。

**Comment by yoshiosakamoto** [comment]
福岡県から表示を変更してほしいという依頼がありました。

円グラフにカーソルを合わせた時に表示される文字を以下に変更してもらえますでしょうか？

・福岡市
「市外在住or情報なし」を「福岡市内」に変更
 ・北九州市
「市外在住or情報なし」を「北九州市内」に変更
・福岡県（その他）
「県外在住or情報なし」はそれ以外に移動（基本無いはず？）
・それ以外
「調査中」を「それ以外」に変更

「※居住地が調査中、海外の陽性患者」を
「※居住地が調査中、県外在住、海外の陽性患者」に変更

ご確認のほどよろしくお願いします。

**Comment by NM502i** [comment]
@yoshiosakamoto 
こちら取り掛かります、しばらくお待ち下さい。

**Comment by NM502i** [comment]
@yoshiosakamoto 
大変遅くなりましたが修正版をコミットしましたのでご確認ください。
なお居住地が分類しにくいデータが数件あったため、とりあえず以下のように処理しました。

- no. 58 居住地：山口県下関市 → 「その他」の「それ以外」にカウント
- no. 64 居住地：山口県下関市 → 「その他」の「それ以外」にカウント
- no. 73 居住地：北九州市外 → 「その他」の「それ以外」にカウント
- no. 96 居住地：福岡県 → 「福岡県」の「福岡県内」にカウント
- no. 96 居住地：福岡県 → 「福岡県」の「福岡県内」にカウント

修正が必要でしたら再度対応しますのでこちらもご確認ください。

**Comment by uttnaoki** [comment]
本番環境で動作していることを確認したため、closeします。
