### ISSUE TITLE
一定以下の画面サイズだと、陽性患者数（居住地別）の表示が乱れる

### ISSUE THREAD

**Issue by NM502i** [Code-for-Fukuoka/covid19-fukuoka#57]
## 起こっている問題 / The Problem
-ブラウザの画面横が一定以下（390px）のサイズになると、 陽性患者数（居住地別）カードの表示が乱れる
## スクリーンショット / Screenshot
![layout_error_01](https://user-images.githubusercontent.com/48637162/81377612-dc689f80-9140-11ea-8d5a-6057f5cab05d.png)
![layout_error_02](https://user-images.githubusercontent.com/48637162/81377120-cc03f500-913f-11ea-9d31-5def70482c49.png)

## 期待する見せ方・挙動 / Expected Behavior
サイズが390px以下になっても、表示が乱れないように修正する
![layout_error_01_fix](https://user-images.githubusercontent.com/48637162/81377390-564c5900-9140-11ea-954c-1ae6dd15604f.png)
![layout_error_02_fix](https://user-images.githubusercontent.com/48637162/81377397-59dfe000-9140-11ea-8b03-41d32ee47710.png)

## 動作環境・ブラウザ / Environment
- macOS /  iOS 
- Chrome / Safari / Firefox

**Comment by uttnaoki** [comment]
これってもう修正されてますよね？

**Comment by NM502i** [comment]
#58のcloseに伴いこちらもcloseします。
