### ISSUE TITLE
陽性患者数（居住地別）の居住地別表示で、最新の陽性患者数が正しく表示されていない

### ISSUE THREAD

**Issue by NM502i** [Code-for-Fukuoka/covid19-fukuoka#58]
## 起こっている問題 / The Problem
- 陽性患者数（居住地別）の居住地別表示で、新規陽性患者数が0人の場合、0人と表示されず、最後にカウントされた新規陽性患者の数が表示されている。
## スクリーンショット / Screenshot
![count_error_01_01](https://user-images.githubusercontent.com/48637162/81379099-77fb0f80-9143-11ea-93b3-f4d4e36164b8.png)
![count_error_01_02](https://user-images.githubusercontent.com/48637162/81379105-7b8e9680-9143-11ea-9bbd-f92f00f749a9.png)
## 期待する見せ方・挙動 / Expected Behavior
新規感染者数が0人の場合は0とカウントされ、日別・累計ともに最新の数字を正しく表示する
![count_error_01_fix](https://user-images.githubusercontent.com/48637162/81379253-b7c1f700-9143-11ea-9eb9-386bcf722d14.png)
## 動作環境・ブラウザ / Environment
- macOS /  iOS 
- Chrome / Safari / Firefox

**Comment by uttnaoki** [comment]
居住地別 では無い方の 陽性患者数 もですが
ここの数値は新規感染者数を表示するんですね。
累計なのか、新規なのか、選択した日の数値なのか、
パッと見で分かりにくいので(今となっては数値の大きさで判断はできますが)
数値の上部の"福岡市(日別)"を"新規感染者(福岡市)"といった言葉に変更するか、
数値の前に"+"を記載した方が分かりやすいのかなと思いました。

**Comment by NM502i** [comment]
@uttnaoki 
確かに「日別」だと機械的すぎて直感的に意味が伝わりにくいですね。
#54 の改修作業に合わせて、こちらも変更したいと思います。

**Comment by NM502i** [comment]
@uttnaoki 
こちらアドバイスを参考に表記の変更を行いました。

**Before :
・ 居住地（日別/累計）：n人**
**After : 
・新規感染者 : +n人
・累計感染者：n人**

また新規感染者が1人以上発生した場合は数字が赤色に、0人の場合は青色になるよう修正しました。

![01](https://user-images.githubusercontent.com/48637162/82139828-b2f8f380-9865-11ea-8887-7c2d98b5f635.png)
![02](https://user-images.githubusercontent.com/48637162/82139831-ba200180-9865-11ea-9a13-1b3682667f76.png)

**Comment by uttnaoki** [comment]
@NM502i 
直観的にわかりやすい工夫があっていいですね。
横から挟んだ意見を参考にしてくださりありがとうございます。
バグが修正できているのであれば反映後、closeしてよいと思います。

**Comment by NM502i** [comment]
@uttnaoki 
こういう箇所は自分で作っていると良し悪しがわからなくなることが多いので、ご意見いただければ助かります。
本番環境で修正を確認したため、こちらのIssuesはcloseします。
