### ISSUE TITLE
相談手順のフローページを改修したい

### ISSUE THREAD

**Issue by NM502i** [Code-for-Fukuoka/covid19-fukuoka#59]
## 改善詳細 / Details of Improvement
- 新型コロナウイルスの相談や受診の目安を厚生労働省が改訂したため、それに合わせ福岡県も改訂する場合は、フローページを改訂版に合わせて改修したい

## 期待する見せ方・挙動 / Expected behavior
- 今後も改訂が行われる可能性があるため、configデータを修正すればフローページの内容を変更できるよう改良したい

**Comment by uttnaoki** [comment]
この相談手順のページは福岡県関係のページを基に作っているんですか？
それとも全国（東京都など）のページを基に作っているんですか？
この相談手順のページに載せる情報はどのソースを使ったらいいんだろうと思いました。

**Comment by yoshiosakamoto** [comment]
@NM502i
相談の基準は以下をベースに作ってほしいと福岡県から依頼がありました。
[https://www.mhlw.go.jp/content/000628620.pdf](url)
福岡県からは以下でどうだろうか？と言われています。
![change](https://user-images.githubusercontent.com/19700507/82033013-11dc3280-96d7-11ea-8ab6-e8d5bcfb743d.png)
修正を検討頂けますでしょうか？

**Comment by NM502i** [comment]
@yoshiosakamoto 
修正しましたのでご確認をお願いいたします。
![03](https://user-images.githubusercontent.com/48637162/82139874-1aaf3e80-9866-11ea-843e-24da44639d8b.png)
![04](https://user-images.githubusercontent.com/48637162/82139876-200c8900-9866-11ea-95ac-743d02288796.png)

**Comment by NM502i** [comment]
本番環境で修正を確認したためこちらcloseします。
※設定ファイルで内容を変更できる改修を近日中に実施予定です。
