### ISSUE TITLE
検査実施数に可視化する日数を固定する

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#66]
## 改善詳細 / Details of Improvement
- 現状、1月からのデータ全てが可視化されているため、そろそろ表示日数に制限かけたほうが良いのではという提案です。
- 東京版を参考にするなら2ヶ月分の表示がきれいかなと思います。
- もしこれを実施するならデータ作成の部分で対応するのが一番良いと思いますが index.vue でデータ整形を行うことでも対応できます。

## スクリーンショット / Screenshot
- 東京版  
  <img width="400" alt="スクリーンショット 2020-05-16 21 05 26" src="https://user-images.githubusercontent.com/16728090/82119384-ff3a2a00-97b8-11ea-8b93-2822349d7448.png">
- 現在の福岡版
  <img width="400" alt="スクリーンショット 2020-05-16 20 58 00" src="https://user-images.githubusercontent.com/16728090/82119387-0b25ec00-97b9-11ea-9698-6b58173b5a4a.png">
- 表示期間を2ヶ月にした福岡版
  <img width="400" alt="スクリーンショット 2020-05-16 21 03 29" src="https://user-images.githubusercontent.com/16728090/82119393-1f69e900-97b9-11ea-9aae-bff3bebd441c.png">

**Comment by yoshiosakamoto** [comment]
@uttnaoki 
ご提案ありがとうございます。表示が気になっていたところでした。
福岡県版のdata.jsonをダウンロードして分析に使っている方もいるようですので、
できれば、表示側でコントロールできるとありがたいです。

**Comment by uttnaoki** [comment]
@yoshiosakamoto 
プルリクを出しましたので確認をお願いします。
（eslintのチェックがなかなか突破できず、余計なcommitが増えてしまいました。。。）

**Comment by uttnaoki** [comment]
@yoshiosakamoto 
すみません、先程出したプルリクについて、
累計表示で２ヶ月前までのデータが反映されていなかったため、プルリクをcloseしました。

**Comment by uttnaoki** [comment]
プルリクを出しましたので確認をお願いします。

**Comment by uttnaoki** [comment]
マージありがとうございます。クローズします。
