### ISSUE TITLE
index.vueのコメントアウトの削除または説明記載

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#67]
## 改善詳細 / Details of Improvement
- index.vueに3つ程、説明のないコメントアウトがあります。
- どうゆう経緯で残されているのかわかりませんが、必要でなければ消したいです。
- もしあえて残しているのであれば説明のコメントを記載していただきたいです。

## スクリーンショット / Screenshot
- １つ目
  <img width="959" alt="スクリーンショット 2020-05-16 21 18 52" src="https://user-images.githubusercontent.com/16728090/82119650-3a3d5d00-97bb-11ea-8a7f-57b5e18f7348.png">
- ２つ目
  <img width="936" alt="スクリーンショット 2020-05-16 21 19 13" src="https://user-images.githubusercontent.com/16728090/82119655-3f021100-97bb-11ea-8d99-92d131215467.png">
- ３つ目
  <img width="959" alt="スクリーンショット 2020-05-16 21 19 26" src="https://user-images.githubusercontent.com/16728090/82119660-41fd0180-97bb-11ea-9031-5138421ded2d.png">

**Comment by yoshiosakamoto** [comment]
コメント削除しました。
