### ISSUE TITLE
年代別・性別グラフを追加する

### ISSUE THREAD

**Issue by NM502i** [Code-for-Fukuoka/covid19-fukuoka#72]
## 改善詳細
- 感染の傾向を把握するため、陽性患者を年代別・性別で分けたグラフを追加したい

## スクリーンショット
**・縦グラフの場合**
![01](https://user-images.githubusercontent.com/48637162/82279995-cc668080-99c8-11ea-8d30-347e3e48476b.png)

**・横グラフの場合**

![02](https://user-images.githubusercontent.com/48637162/82280000-d25c6180-99c8-11ea-89e0-778fa2164c6a.png)

## 決めてほしいこと（実装する場合）
- 縦グラフ/横グラフのどちらにするか（区分けが多すぎるため、円グラフは非推奨）
- 性別グラフの色分けについて（今のところ男性を青・女性を赤に設定しているが、福岡県のジェンダー規範に合わせて問題はないか）

その他変更すべき箇所があればご指摘ください

**Comment by yoshiosakamoto** [comment]
個人的には縦が好みです。

**Comment by yoshiosakamoto** [comment]
色の件含め福岡県に確認中です。

**Comment by uttnaoki** [comment]
なんとなく赤が黒っぽいですね。
円グラフのカードに使われている色が明るくて柔らかい印象があったので、
あんな感じがいいんじゃないかなぁと思いました。(青単色を期待しているわけではないです)

**Comment by yoshiosakamoto** [comment]
グラフ自体はOKですが、色は工夫してほしいとの事です。。。

>伝統的な性別認識による色分けとなってしまうため、
>行政が関係しているサイトの表示としてはふさわしくないとのことでした。
>工夫して作成していただけますと幸いです。

サイトはブルー系ですので、それに合わせた濃い色と薄い色にするか、
ジェンダーニュートラルカラーにするかでしょうか？
https://www.jafca.org/colortrend/ladieswear/2018SS.html

何か良い案があればお願いします。

**Comment by NM502i** [comment]
@yoshiosakamoto 
大変遅くなりましたが後ほど修正版を提案します。

**Comment by NM502i** [comment]
@yoshiosakamoto 
内閣府の男女共同参画局のサイトで配布されている資料を基に色を修正しました。

男女共同参画の視点からの防災研修プログラム
http://www.gender.go.jp/policy/saigai/bosai_kenshu.html
→男女共同参画の視点からの防災研修（p17を参照）
http://www.gender.go.jp/policy/saigai/pdf/kenshu_kihon_zentai.pdf


**・縦グラフの場合**
![01](https://user-images.githubusercontent.com/48637162/83467833-0306c580-a4b6-11ea-951e-e15883d12ef1.png)
**・横グラフの場合**
![02](https://user-images.githubusercontent.com/48637162/83467843-07cb7980-a4b6-11ea-8d39-ac1462ebc42a.png)

**Comment by yoshiosakamoto** [comment]
グラフOKとなりました！
developmentに反映して頂けますでしょうか？
縦、横はお任せとの事ですが、他と合わせるなら縦かな？
という感じです。

**Comment by NM502i** [comment]
修正版をdevelopmentに反映しました

**Comment by yoshiosakamoto** [comment]
本番環境に反映したのでクローズします。
