### ISSUE TITLE
ブラウザで特定の操作を行うと、検査実施数のカードが表示されなくなる

### ISSUE THREAD

**Issue by NM502i** [Code-for-Fukuoka/covid19-fukuoka#75]
## 起こっている問題
1. https://fukuoka.stopcovid19.jp/ にアクセスする
2. トップページ（福岡県内の感染動向ページ）表示後、サイト内の別ページ（「当サイトについて」など）に遷移する
3. 別ページに遷移後、トップページに戻る
4. 「検査実施数」のカードが表示されなくなる

## スクリーンショット

![error01](https://user-images.githubusercontent.com/48637162/82720867-7ceac200-9cf2-11ea-943f-b9a329e90755.png)
![error02](https://user-images.githubusercontent.com/48637162/82720870-883ded80-9cf2-11ea-8500-e221cf8d596e.png)

## 推定される不具合の原因
**推定理由：**
TimeStackedBarChart.vueにおいて、propsに保存されているデータを直接編集している。
propsのデータを変更すると親データも変更されるため、ページを再度読み込んだ際にキャッシュが残っていれば、変更済みの親データを再度編集することになり不具合が発生する。

**箇所（TimeStackedBarChart.vueの108-116行）：**

>     // 可視化しないラベルを削除
>     this.labels.splice(0, startIndex)
>     // 区域の毎にループ
>     for (const i in this.chartData) {
>       // 可視化しないデータを削除しつつ、可視化しないデータの累計値を計算
>       this.hiddenDataSum.push(this.sum(this.chartData[i].splice(0, startIndex)))
>       // 累積データを計算
>       this.cumulativeData.push(this.cumulative(this.chartData[i], i))
>     }

## 期待する見せ方・挙動
- サイト内の別ページに遷移後、福岡県内の感染動向ページに戻っても、検査実施数のカードが表示されるよう修正する

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Chrome / Safari / Firefox

**Comment by NM502i** [comment]
@uttnaoki 
@yoshiosakamoto 
こちら私の担当箇所ではありませんが、やや緊急性が高そうなbugだったために、取り急ぎこちらで応急処置&developmentにコミットしておきました。
もっと良さそうな修正方法があれば対応をお願いします。

**Comment by uttnaoki** [comment]
@NM502i 
早々にバグ発見・修正の対応をしていただきありがとうございます。
前回の自分の修正について、vueに関する知識が足りてませんでした。勉強になります。
他のカードについても可視化期間に関する修正を加えるつもりだった為、
事前により良い修正方法を知れてよかったです。

まだissuesとして上げてませんが、
お時間がありましたらその他のカード(棒グラフ)についても可視化期間に関する修正をして頂きたいです。

**Comment by NM502i** [comment]
@uttnaoki 
修正自体は問題ありませんが、データ表示が直近2ヶ月間に固定され、過去データが参照できない現在の仕様について、何か特別な理由はありますでしょうか。

例えば東京都のサイトを見ても、確かにトップ画面のグラフ表示期間は直近2ヶ月間のものですが、グラフを横スクロールすれば過去のデータが確認できるようになっており、他の都道府県のサイトも、（操作方法は違っていても）一定期間以前の過去データを参照できないという仕様は、確認した限り存在しません。

デフォルトの表示期間を直近2ヶ月にするのは問題ないと思いますが、何か特別な理由がなければ、修正の際、東京都や他の都道府県のサイトのように
・ユーザーの操作で過去のデータも確認できるようにする
仕様を追加したいと思っていますが、よろしいでしょうか。

**Comment by uttnaoki** [comment]
@NM502i 
表示範囲をスクロール無しの2ヶ月に限定した理由については
東京版のソースを模倣するには編集する部分が多く、実装が困難と考えたため
現在のような仕様にしました。
(あと、何も検証をしていないただの予想なのですが
全データをグラフ化すると後々動作が重くなるのではないか とも思いました。)

ユーザー操作による過去データの参照を東京版のように実装できる、または、より簡潔な方法で実装できるのであれば
実装した方が良いと思います。

**Comment by NM502i** [comment]
@uttnaoki 
それでは陽性患者数について以下の修正作業を行います。

**1. デフォルトの表示期間を直近の2ヶ月間にする
2. 過去データを参照できる機能を追加する**

1 については、作成いただいたコードを外部スクリプト化して使わせてもらう予定なので
・新型コロナウイルス感染症　帰国者・接触者相談センター相談件数
についても修正を行っておきます。

最短で明日の朝にはdevelompent上で確認を行えるかと思います。

**Comment by uttnaoki** [comment]
@NM502i 
ありがとうございます。
無理のない程度に作業をお願いします。

元の自分のコードに合わせて修正する必要は無いので、
上記バグを発生させず、より簡単な書き方があればそちらを採用して頂きたいです🙆‍♂️

**Comment by yoshiosakamoto** [comment]
@NM502i ありがとうございます！
本番環境に反映しました。
問題なさそうであればクローズしてください。

**Comment by NM502i** [comment]
ちょっと作業遅れて今日中の対応になります。
