### ISSUE TITLE
陽性患者数 の可視化期間を2ヶ月にする

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#76]
## 改善詳細 / Details of Improvement
- 検査実施数 のように可視化する期間(横軸の範囲)を2ヶ月にする。

**Comment by uttnaoki** [comment]
@NM502i 
スクロールの件、実装できそうでしょうか？
時間がかかりそうであればとりあえず、
各棒グラフの横軸の表示範囲だけ統一した方がよいと思うのですが
いかがでしょうか？

**Comment by NM502i** [comment]
@uttnaoki 
大変遅くなりましたが以下の変更と機能追加を行いました。

- グラフの表示期間を2ヶ月間に設定、あわせて表示期間を設定できるスライダーを追加
- グラフ表示を現行のエリア選択型から積み上げ型グラフに変更

![03](https://user-images.githubusercontent.com/48637162/83366997-3af60600-a3ed-11ea-8dfa-30b1154105bb.png)

**Comment by NM502i** [comment]
検査実施数にも同様の機能を追加
![02](https://user-images.githubusercontent.com/48637162/83367106-c53e6a00-a3ed-11ea-8a01-abb181189c8b.png)

**Comment by yoshiosakamoto** [comment]
かっこいい！

**Comment by yoshiosakamoto** [comment]
本番環境に反映しましたのでクローズします。
