### ISSUE TITLE
新型コロナウイルス感染症　帰国者・接触者相談センター相談件数 の可視化期間を2ヶ月にする

### ISSUE THREAD

**Issue by uttnaoki** [Code-for-Fukuoka/covid19-fukuoka#77]
## 改善詳細 / Details of Improvement
- 検査実施数 のように可視化する期間(横軸の範囲)を2ヶ月にする

**Comment by NM502i** [comment]
グラフの表示期間を2ヶ月間に設定、あわせて表示期間を設定できるスライダーを追加
（#76と同様）

![01](https://user-images.githubusercontent.com/48637162/83367043-7b558400-a3ed-11ea-93e1-57ff5ec21072.png)

**Comment by yoshiosakamoto** [comment]
本番環境に反映したのでクローズします。
