### ISSUE TITLE
陽性患者数の感染経路別」のグラフ

### ISSUE THREAD

**Issue by yoshiosakamoto** [Code-for-Fukuoka/covid19-fukuoka#81]
## 改善詳細 / Details of Improvement
- 福岡県からの依頼
　感染経路別（感染経路不明、濃厚接触者、海外渡航歴あり）のグラフを作成してほしい

## 期待する見せ方・挙動 / Expected behavior
現在のグラフは市町村別なので、それを「感染経路別」に変更するイメージ

**Comment by nyoshimatsu** [comment]
data.jsonの"patients"の中に、"感染経路"の項目を追加しました。

感染経路の項目の値は、下記の文字列としています。
・"感染経路不明"
・"濃厚接触者"
・"海外渡航歴有"
・空白（上記のいづれの項目が1でない場合）

data.jsonでは、以下のような内容です。

    "patients": {
        "date": "2020\/06\/08 10:53",
        "data": [
            {
                "リリース日": "2020-02-20T00:00:00Z",
                "曜日": 0,
                "居住地": "福岡市中央区",
                "年代": "60代",
                "性別": "男性",
                "退院": "",
                "感染経路": "感染経路不明",
                "date": "2020-02-20"
            },

**Comment by NM502i** [comment]
jsonを改修いただいたので、どなたもアサインされてなければグラフ作成します。

**Comment by yoshiosakamoto** [comment]
@NM502i  いつもすみません。できればお願いします。

福岡市版もグラフの期間制限を入れてほしいと福岡市から依頼が来ています。
福岡県版を移植しようと思っていますが、分からないところが出てきたら教えてください。

**Comment by NM502i** [comment]
@yoshiosakamoto 
陽性患者数の感染経路別グラフを作成し、developmentにcommitしておきました。
カード右上の表示については下記の福岡県のサイトを参考に、直近7日間の感染経路不明者の割合を表示しています。
https://www.pref.fukuoka.lg.jp/contents/covid19-hassei.html

修正点・変更点がありましたら対応しますので確認のほどお願いします。

![001](https://user-images.githubusercontent.com/48637162/84440399-e1a39780-ac74-11ea-84e6-229d18449c32.png)

**Comment by yoshiosakamoto** [comment]
ありがとうございます！
福岡県に確認します。

**Comment by yoshiosakamoto** [comment]
県の確認取れていませんが、公開したので一旦クローズします。
